name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  app:
    name: Home Assistant app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: frenck/action-app-linter@v2
        with:
          path: ./mqtt-viewer
